---
# Demo playbook
- name: Configuring Tenant
  hosts: apic
  gather_facts: no

  vars:
    aci_login: &aci_login
      hostname: "{{ aci_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
    tenant: Ansible
    vrf: vrf_ansible
    bd:
      name: bd_ansible_1
      ip: 9.9.9.1
      mask: 24

    app_profile: app1
    filter: Contract1_filter
    filter_entry: Contract1_entry
    contract: Contract1
    contract_subject: Subject1
    epg1: web_epg
    epg2: db_epg
    vmm_domain: Pod1

  tasks:
  - name: Create Tenant
    aci_tenant:
      <<: *aci_login
      tenant: "{{ tenant }}"
      description: 'tenant'
      state: present
    delegate_to: localhost

  - name: Create VRF
    aci_vrf:
      <<: *aci_login
      tenant: "{{ tenant }}"
      vrf_name: "{{ vrf }}"
      state: present
    delegate_to: localhost

  - name: Creating BD
    aci_bd:
      <<: *aci_login
      tenant: "{{ tenant }}"
      vrf: "{{ vrf }}"
      bd: "{{ bd.name }}"
      gateway_ip: "{{ bd.ip }}"
      subnet_mask: "{{ bd.mask }}"
      state: present
    delegate_to: localhost

  - name: Create AP
    aci_ap:
      <<: *aci_login
      tenant: "{{ tenant_name }}"
      app_profile: "{{ app_profile }}"
      state: present
    delegate_to: localhost

  - name: Create web_epg
    aci_epg:
      <<: *aci_login
      tenant: "{{ tenant }}"
      bd: "{{ bd.name }}"
      app_profile: "{{ app_profile }}"
      epg: "{{ epg1 }}"
      contract_name_provider: "{{ contract }}"
      contract_name_consumer: "{{ contract }}"
      contract_type: both
      state: present
    delegate_to: localhost

  - name: Create db_epg
    aci_epg:
      <<: *aci_login
      tenant: "{{ tenant }}"
      app_profile: "{{ app_profile }}"
      epg: "{{ epg2 }}"
      bd: "{{ bd.name }}"
      contract_name_provider: "{{ contract }}"
      contract_name_consumer: "{{ contract }}"
      contract_type: both
      state: present
    delegate_to: localhost

  - name: Create Filter
    aci_filter:
      <<: *aci_login
      tenant: "{{ tenant }}"
      filter: "{{ filter }}"
      state: present
    delegate_to: localhost

  - name: Create Filter Entry
    aci_filter_entry:
      <<: *aci_login
      tenant: "{{ tenant }}"
      filter: "{{ filter }}"
      filter_entry: "{{ filter_entry }}"
      state: present
    delegate_to: localhost

  - name: Create Tenant Contract
    aci_contract:
      <<: *aci_login
      tenant: "{{ tenant }}"
      contract: "{{ contract }}"
      scope: tenant
      state: present
    delegate_to: localhost

  - name: Create Contract Subjects
    aci_contract_subjects:
      <<: *aci_login
      tenant: "{{ tenant }}"
      filter: "{{ filter }}"
      contract: "{{ contract }}"
      contract_subject: "{{ contract_subject }}"
      reverse_filter: yes
      state: present
    delegate_to: localhost

  - name: Deploying EPG
    aci_epg_to_domain:
      <<: *aci_login
      tenant: "{{ tenant }}"
      app_profile: "{{ app_profile }}"
      epg: "{{ item }}"
      domain: vmm
      domain_profile: "{{ vmm_domain }}"
      deploy_immediacy: immediate
      state: present
    with_items:
    - '{{ epg1 }}'
    - '{{ epg2 }}'
    delegate_to: localhost
