---
- name: aci playbook testing 
  hosts: apic
  connection: local
  gather_facts: no


  tasks:

    - name: fabric topology
      aci_fabric_inventory:
         node_id : 101
         level: brief
         filename: test_1
         host: "{{ inventory_hostname}}"
         username: "{{ user }}"
         password: "{{ pass }}"
