---

- name: playbook for aci testing
  hosts: apic
  connection: local
  gather_facts: no

  vars:
      inventory_hostname: 172.31.186.184
      user: admin
      passwd: Cisco!123
      tenant:
          - { name: 'QA-Customer1-Tenant' }
      application_profile:
          - { name: 'QA-Customer1-AppProfile' }
      epg:
          - { name: 'QA-Customer1-EPG' }
          - { name: 'QA-Customer2-EPG' }
      vrf:
          - { name: 'QA-Customer1-VRF' }
      bd:
          - { name: 'QA-Customer1-BD', arp_flooding: 'yes' }
      attachable_entity_profile:
          - { name: 'QA-Customer1-AEP' }
      leaf_access_port_policy_group: 
          - { name: 'QA-Customer-Nishanth-LAPPG', aep_leaf: 'QA-Customer1-AEP' }
      leaf_interface_profile:
          - { name: 'QA-Customer-Nishanth-IP', interface_selector: 'QA-Nishanth-IS', lappg: 'QA-Customer-Nishanth-LAPPG', port: '28' }

  tasks:
    - name: generate_tenant_config_file
      aci_generate_xml:
          tenant: "{{ item[0].name }}"
          application_profile: "{{ item[1].name }}"
          epg: "{{ item[2].name }}"
          vrf: "{{ item[3].name }}"
          bd: "{{ item[4].name }}"
          arp_flooding: "{{ item[4].arp_flooding }}"
          attachable_entity_profile: "{{ item[5].name }}"
          leaf_access_port_policy_group: "{{ item[6].name }}"
          aep_leaf: "{{ item[6].aep_leaf }}"
          leaf_interface_profile: "{{ item[7].name }}"
          interface_selector: "{{ item[7].interface_selector }}"
          lappg: "{{ item[7].lappg }}"
          port: "{{ item[7].port }}"
      with_nested: 
          - "{{ tenant }}"
          - "{{ application_profile }}"
          - "{{ epg }}"
          - "{{ vrf }}"
          - "{{ bd }}"
          - "{{ attachable_entity_profile }}"
          - "{{ leaf_access_port_policy_group }}"
          - "{{ leaf_interface_profile }}"

    - name: add a tenant '''QA-Customer1-Tenant'''
      aci_rest: 
        action: post 
        uri: /api/mo/uni.xml 
        config_file: /home/swetha/ansible/aci-ansible/configs/tenant_QA-Customer1-Tenant.xml
        host: "{{ inventory_hostname }}" 
        username: "{{ user }}" 
        password: "{{ passwd }}"

    - name: add a App
      aci_rest:
        action: post
        uri: /api/mo/uni.xml
        config_file: /home/swetha/ansible/aci-ansible/configs/application_profile_QA-Customer1-AppProfile.xml
        host: "{{ inventory_hostname }}"
        username: "{{ user }}"
        password: "{{ passwd }}"

    - name: add a epg
      aci_rest:
        action: post
        uri: /api/mo/uni.xml
        config_file: /home/swetha/ansible/aci-ansible/configs/epg_QA-Customer1-EPG.xml
        host: "{{ inventory_hostname }}"
        username: "{{ user }}"
        password: "{{ passwd }}"

    - name: add a vrf
      aci_rest:
        action: post
        uri: /api/mo/uni.xml
        config_file: /home/swetha/ansible/aci-ansible/configs/vrf_QA-Customer1-VRF.xml
        host: "{{ inventory_hostname }}"
        username: "{{ user }}"
        password: "{{ passwd }}"

    - name: add a aep
      aci_rest:
        action: post
        uri: /api/mo/uni.xml
        config_file: /home/swetha/ansible/aci-ansible/configs/aep_QA-Customer1-AEP.xml
        host: "{{ inventory_hostname }}"
        username: "{{ user }}"
        password: "{{ passwd }}"
 
    - name: add a lappg
      aci_rest:
        action: post
        uri: /api/mo/uni.xml
        config_file: /home/swetha/ansible/aci-ansible/configs/lappg_QA-Customer-Nishanth-LAPPG.xml
        host: "{{ inventory_hostname }}"
        username: "{{ user }}"
        password: "{{ passwd }}"

    - name: add a lip
      aci_rest:
        action: post
        uri: /api/mo/uni.xml
        config_file: /home/swetha/ansible/aci-ansible/configs/lip_QA-Customer-Nishanth-IP.xml
        host: "{{ inventory_hostname }}"
        username: "{{ user }}"
        password: "{{ passwd }}"


