---

- name: playbook for aci tenant bridge domain
  hosts: apic
  connection: local
  gather_facts: no

  vars:
   proxy_env:
      http_proxy: http://proxy.esl.cisco.com:8080
      https_proxy: https://proxy.esl.cisco.com:8080

  tasks:

   - name: aci bd cobra
     aci_bd: 
      name: Green_bd1
      context: greenVRF
      tenant: Green 
      arpFlood: yes 
      l2_unicast: flood
      l3_multicast: flood
      multi_dest: encap-flood
      unicast_routing: yes
      state: present
      host: "{{ inventory_hostname }}"
      username: "{{ user }}"
      password: "{{ pass }}"
