---
- name: Playbook for aci_rest testing
  hosts: apic
  gather_facts: no

  tasks:
  - name: Add tenant
    aci_rest:
      hostname: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      action: post
      config_file: files/aci_config.xml
      uri: /api/mo/uni.xml config
 
  - name: Get tenants
    aci_rest:
      hostname: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      action: get
      uri: /api/node/class/fvTenant.json

  - name: Configure contracts
    aci_rest:
      hostname: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      action: post
      config_file: files/contract_config.xml
      uri: /api/mo/uni.xml config
