---

- name: playbook for aci testing
  hosts: apic
  connection: local
  gather_facts: no

  vars:
      inventory_hostname: 172.31.186.184
      user: admin
      passwd: Cisco!123
      tenant:
          - { name: QA-Customer-Nishanth  }
      application_profile:
          - { name: QA-Customer-Nishanth }
