---

- name: playbook for aci testing
  hosts: apic
  connection: local
  gather_facts: no

  vars:
      inventory_hostname: 172.31.186.184
      user: admin
      passwd: Cisco!123
      tenant:
          - { name: 'QA-Customer1-Tenant' }
      application_profile:
          - { name: 'QA-Customer1-AppProfile' }
      epg:
          - { name: 'QA-Customer1-EPG' }
          - { name: 'QA-Customer2-EPG' }


  tasks:
    - name: add a tenant
      aci_rest: action=post uri=/api/mo/uni.xml config_file=/home/swetha/ansible/aci-ansible/configs/tenant_QA-Customer1-Tenant.xml host={{ inventory_hostname }} username={{ user }} password={{ passwd }}

